### ISSUE TITLE
Mock or not to mock guideline's example is actually a stub

### ISSUE THREAD

**Issue by oveddan** [andreareginato/betterspecs#121]
Update that guideline to talk about a mock, using something with 
```ruby
expect(something).to receive
```

Maybe add another guideline describing if you should use a mock or a stub, explaining when to use: 

```ruby
allow(something).to receive 
```
or
 
```ruby
expect(something).to receive

**Comment by onebree** [comment]
@oveddan I am going to close this issue as thje example has been fixed by #124. In regards to adding additional explanations, feel free to submit a PR.
