### ISSUE TITLE
Consider alternative to best practice term

### ISSUE THREAD

**Issue by eliotsykes** [andreareginato/betterspecs#150]
Best practice is a term used in betterspecs. Practices are dependent on context. There can be multiple conflicting but good practices with no clear winner. Best practice misses this nuance unfortunately. Best practice discourages independent and critical thought of the practices presented which is an unintended consequence.

**Comment by onebree** [comment]
I do not mean to be rude, but can you explain this without the word practice? It was a lot for me to comprehend. But then again, I am juggling tasks.

What would you suggest? Guidelines? Style guide? Cookbook?

**Comment by eliotsykes** [comment]
Not rude at all, happy to clarify, I didn't explain well and sorry about that. 

_Best_ practice suggest there's one good practice and all others aren't as good. This often isn't the case. Perhaps _suggested practice_ would be one way of putting it.

**Comment by onebree** [comment]
"Best practice" is also a popular buzz-phrase, which is why it may have been chosen. I agree with it, however, because BetterSpecs involves _practice_, not just use. For example, suggesting gems like Webmock for stubs/mocks. This is a practice. I agree it may not be the _best_ term, but then again, what other RSpec resources (like this one) are out there?

**Comment by eliotsykes** [comment]
This is just a request for consideration to change the docs in a way that may have been a very minor improvement to the project. Admittedly I may be in the minority in thinking this would be a small improvement. 

I have students who use this as a resource and I ask them to read betterspecs but to also form their own opinions. This is why I thought it worth starting a discussion on the use of the term. However, best practice is in widespread use and often not taken literally.

**Comment by onebree** [comment]
@eliotsykes Since you recommend this to your students, do you want to help contribute to the project? As in, become a COLLABORATOR?

**Comment by eliotsykes** [comment]
@onebree I don't know if I have the time though I can try - is there a (small) task I could do? I'll see if I can complete it before 2017 :-)

**Comment by onebree** [comment]
We are looking for a team of maintainers. But I appreciate your humor :-)

**Comment by eliotsykes** [comment]
Ah I see I just saw #146. Is the project looking for translators too?

**Comment by onebree** [comment]
Yes. Any of the current languages we support.

**Comment by eliotsykes** [comment]
Thanks, that's good to know, found languages here: https://github.com/andreareginato/betterspecs/tree/master/content

This would be a great way for newer devs to contribute, I'll try to find some contributors.

**Comment by eliotsykes** [comment]
Just in case its of interest and not been discussed, putting the translations into YAML and adding betterspecs to the public projects here https://github.com/Locale (https://www.localeapp.com/) might gain some translators/maintainers.

**Comment by onebree** [comment]
Okay, can you open a new issue for that request? And explain a little more about it? Like other projects currently doing that. Thank you.
