### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by andreareginato** [andreareginato/betterspecs#47]
- [x] [Factorygirl tips](http://arjanvandergaag.nl/blog/factory_girl_tips.html?utm_source=rubyweekly&utm_medium=email)
- [x] [Shared example variables](https://www.relishapp.com/rspec/rspec-core/v/2-6/docs/example-groups/shared-examples)
- [x] [Do't make my code more testable](http://gmoeck.github.com/2012/07/09/dont-make-your-code-more-testable.html?utm_source=rubyweekly&utm_medium=email)

**Comment by onebree** [comment]
Confirmed: all 3 things have been included in PR #133, on the links partial
